# Generated by Django 5.2.3 on 2025-12-18 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_rating', models.IntegerField(help_text='Rating for the order (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='order rating')),
                ('stay_rating', models.IntegerField(help_text='Rating for the stay/room experience (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='stay rating')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment', null=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.OneToOneField(help_text='The order this feedback is for (unique)', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order', verbose_name='order')),
                ('patient', models.ForeignKey(blank=True, help_text='The patient who provided the feedback (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clinic.patient', verbose_name='patient')),
                ('room', models.ForeignKey(help_text='The room where the order was delivered', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clinic.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedbacks_f_created_98367c_idx'), models.Index(fields=['room', '-created_at'], name='feedbacks_f_room_id_9bf36a_idx')],
            },
        ),
    ]
