# Generated by Django 5.2.3 on 2026-01-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_add_staff_and_update_ratings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedbacks_f_staff_i_5ee187_idx',
            old_name='feedbacks_f_staff_i_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedbacks_f_satisfa_2164b3_idx',
            old_name='feedbacks_f_satisfa_idx',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='order_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='stay_rating',
        ),
    ]
