# Generated by Django 5.2.3 on 2026-03-22 04:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_patient_full_name_and_more'),
        ('feedbacks', '0004_update_feedback_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedbacks_f_satisfa_2164b3_idx',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient_assignment',
            field=models.ForeignKey(blank=True, help_text='The patient assignment this feedback is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clinic.patientassignment', verbose_name='patient assignment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(help_text='The room where the orders were delivered', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clinic.room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff member (nurse) who attended the orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='staff member'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff_rating',
            field=models.IntegerField(default=0, help_text='Rating for staff interaction (0-5 stars)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='staff rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='stay_rating',
            field=models.IntegerField(default=0, help_text='Rating for stay experience (0-5 stars)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='stay rating'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['patient_assignment', '-created_at'], name='feedbacks_f_patient_537610_idx'),
        ),
    ]
