# Generated by Django 5.2.3 on 2025-12-18 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(help_text='Unique device identifier', max_length=255, unique=True, verbose_name='device UID')),
                ('device_type', models.CharField(choices=[('IPAD', 'iPad'), ('WEB', 'Web Browser'), ('OTHER', 'Other')], default='IPAD', help_text='Type of device', max_length=10, verbose_name='device type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active', verbose_name='is active')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this device was seen online', null=True, verbose_name='last seen at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Patient full name', max_length=255, verbose_name='full name')),
                ('phone_e164', models.CharField(help_text='Phone in E.164 format (e.g., +1234567890)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format (e.g., +1234567890). Max 15 digits.', regex='^\\+[1-9]\\d{1,14}$')], verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this patient is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique room code (e.g., 101, A-205)', max_length=50, unique=True, verbose_name='room code')),
                ('floor', models.CharField(blank=True, help_text='Floor number or name', max_length=20, null=True, verbose_name='floor')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this room is currently available', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['code'],
            },
        ),
    ]
