# Generated by Django 5.2.3 on 2025-12-19 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, help_text='Staff members who can view orders from this device', related_name='assigned_devices', to=settings.AUTH_USER_MODEL, verbose_name='assigned staff'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room where this device is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='clinic.room', verbose_name='room'),
        ),
    ]
