# Generated by Django 5.2.3 on 2025-12-20 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_device_assigned_staff_device_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active', verbose_name='is active')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When care started', verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When care ended', null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device used for orders', on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='clinic.device', verbose_name='device')),
                ('patient', models.ForeignKey(help_text='Patient being cared for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clinic.patient', verbose_name='patient')),
                ('room', models.ForeignKey(help_text='Room where patient is located', on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='clinic.room', verbose_name='room')),
                ('staff', models.ForeignKey(help_text='Staff member providing care', on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'patient assignment',
                'verbose_name_plural': 'patient assignments',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['staff', 'is_active'], name='clinic_pati_staff_i_05a51b_idx'), models.Index(fields=['device', 'is_active'], name='clinic_pati_device__0b5ddc_idx'), models.Index(fields=['patient', 'is_active'], name='clinic_pati_patient_527efb_idx')],
            },
        ),
    ]
