# Generated by Django 5.2.3 on 2026-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patientassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassignment',
            name='order_limits',
            field=models.JSONField(blank=True, default=dict, help_text='Order limits by category type (e.g., {"DRINK": 1, "SNACK": 1})', verbose_name='order limits'),
        ),
    ]
