# Generated by Django 5.2.3 on 2026-01-12 19:05

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patientassignment_order_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassignment',
            name='order_limits',
            field=models.JSONField(blank=True, default=clinic.models.get_default_order_limits, help_text='Order limits by category type (e.g., {"DRINK": 1, "SNACK": 1})', verbose_name='order limits'),
        ),
    ]
