# Generated by Django 5.2.3 on 2026-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_patientassignment_survey_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(db_index=True, help_text='Patient full name', max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='patientassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is currently active', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique room code (e.g., 101, A-205)', max_length=50, unique=True, verbose_name='room code'),
        ),
    ]
