# Generated by Django 5.2.3 on 2025-12-18 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0, help_text='Current quantity in stock', validators=[django.core.validators.MinValueValidator(0)], verbose_name='on hand quantity')),
                ('reserved', models.IntegerField(default=0, help_text='Quantity reserved for orders', validators=[django.core.validators.MinValueValidator(0)], verbose_name='reserved quantity')),
                ('reorder_level', models.IntegerField(blank=True, help_text='Minimum quantity before reorder is needed', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='reorder level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balance', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'inventory balance',
                'verbose_name_plural': 'inventory balances',
                'ordering': ['product__category__sort_order', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('WASTE', 'Waste'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('CONSUME', 'Consume')], help_text='Type of inventory movement', max_length=20, verbose_name='movement type')),
                ('quantity', models.IntegerField(help_text='Quantity moved (always positive, sign determined by movement_type)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this movement', verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'inventory movement',
                'verbose_name_plural': 'inventory movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
