# Generated by Django 5.2.3 on 2025-12-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique category name', max_length=100, unique=True, verbose_name='category name')),
                ('sort_order', models.IntegerField(default=0, help_text='Order for displaying categories (lower numbers first)', verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200, verbose_name='product name')),
                ('description', models.TextField(blank=True, help_text='Product description', verbose_name='description')),
                ('image_url', models.URLField(blank=True, help_text='URL to product image', max_length=500, verbose_name='image URL')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (optional)', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('unit_label', models.CharField(default='unidad', help_text='Unit label (e.g., "unidad", "pieza", "botella")', max_length=50, verbose_name='unit label')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
    ]
