# Generated by Django 5.2.3 on 2026-01-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image file', null=True, upload_to='products/', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL to product image (optional, use if not uploading file)', max_length=500, verbose_name='image URL'),
        ),
    ]
