# Generated by Django 5.2.3 on 2026-01-10 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., "Más Popular", "Relajante")', max_length=50, unique=True, verbose_name='tag name')),
                ('color', models.CharField(default='#C78650', help_text='Hex color code for the tag (e.g., "#C78650")', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, help_text='Icon emoji or icon name (optional)', max_length=50, verbose_name='icon')),
                ('sort_order', models.IntegerField(default=0, help_text='Order for displaying tags (lower numbers first)', verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__sort_order', 'product_sort_order', 'name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Product benefits as JSON array: [{"icon": "❤️", "text": "Inmunidad Fuerte"}]', verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_description',
            field=models.TextField(blank=True, help_text='Custom description for featured section (optional)', verbose_name='featured description'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_title',
            field=models.CharField(blank=True, help_text='Custom title for featured section (optional)', max_length=200, verbose_name='featured title'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured product (product of the month/week)', verbose_name='is featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sort_order',
            field=models.IntegerField(default=0, help_text='Order for displaying products within category (lower numbers first)', verbose_name='product sort order'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Product rating (0-5 stars)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings received', validators=[django.core.validators.MinValueValidator(0)], verbose_name='rating count'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='carousel_order',
            field=models.IntegerField(default=0, help_text='Order for displaying in carousel (lower numbers first)', verbose_name='carousel order'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon emoji or icon name for category (e.g., "🍵", "🍪", "🍓")', max_length=50, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_in_carousel',
            field=models.BooleanField(default=True, help_text='Whether to show this category in kiosk carousel', verbose_name='show in carousel'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Product tags/badges (e.g., "Más Popular", "Orgánico")', related_name='products', to='catalog.producttag', verbose_name='tags'),
        ),
    ]
