# Generated by Django 5.2.3 on 2026-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_producttag_alter_product_options_product_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('DRINK', 'Bebidas'), ('SNACK', 'Snacks'), ('OTHER', 'Otros')], default='OTHER', help_text='Category type for order limits (DRINK, SNACK, or OTHER)', max_length=20, verbose_name='category type'),
        ),
    ]
