# Generated by Django 5.2.3 on 2026-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_food_category_and_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image file for category (PNG/JPG). Recommended size 64x64, square, transparent background.', null=True, upload_to='category-icons/', verbose_name='icon image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('DRINK', 'Bebidas'), ('SNACK', 'Snacks'), ('FOOD', 'Comida'), ('OTHER', 'Otros')], default='OTHER', help_text='Category type for order limits (DRINK, SNACK, or OTHER)', max_length=20, verbose_name='category type'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon emoji or icon name for category (e.g., "🍵", "🍪", "🍓"). Deprecated in favor of icon_image.', max_length=50, verbose_name='icon'),
        ),
    ]
