# Generated by Django 5.2.3 on 2025-12-18 13:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', help_text='Current order status', max_length=20, verbose_name='status')),
                ('placed_at', models.DateTimeField(auto_now_add=True, help_text='When the order was placed', verbose_name='placed at')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the order was delivered', null=True, verbose_name='delivered at')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the order was cancelled', null=True, verbose_name='cancelled at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Device (iPad/Kiosk) that placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clinic.device', verbose_name='device assignment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clinic.patient', verbose_name='patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clinic.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_label', models.CharField(help_text='Snapshot of product unit label at time of order', max_length=50, verbose_name='unit label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Previous status (empty for initial status)', max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(help_text='New status', max_length=20, verbose_name='to status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the status change occurred', verbose_name='changed at')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this status change', verbose_name='note')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order status event',
                'verbose_name_plural': 'order status events',
                'ordering': ['-changed_at'],
            },
        ),
    ]
