# Generated by Django 5.2.3 on 2025-12-20 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patientassignment'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patient_assignment',
            field=models.ForeignKey(blank=True, help_text='Patient assignment at the time of order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clinic.patientassignment', verbose_name='patient assignment'),
        ),
    ]
