# Generated by Django 5.2.3 on 2026-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_patient_full_name_and_more'),
        ('orders', '0002_order_patient_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', help_text='Current order status', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='idx_order_status_placed'),
        ),
    ]
